name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main, add-ci-cd ] # Added a test branch to check execution of actions

jobs:
  test_suite:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: python -m pytest -v

  train_and_quantize:
    name: Train Model and Run Quantization
    runs-on: ubuntu-latest
    needs: test_suite
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python ./src/train.py

      - name: Run quantization script
        run: python ./src/quantize.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: trained_models/

  build_and_test_container:
    name: Build and Test Docker Container
    runs-on: ubuntu-latest
    needs: train_and_quantize
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: trained_models/

      - name: Build Docker image
        run: docker build -t mlops-img .

      - name: Run Docker container for verification
        run: docker run --rm mlops-img